---

- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install basic system packages
  apt:
    name: 
      - curl
      - wget
    state: latest
    update_cache: true

- name: Install and configure NGINX proxy server
  include_tasks: nginx.yml